extends Node

const LEVELS := {
	1: [
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                           MMMMMM                               ",
		"                                                                                                                                                           MMMMMM                               ",
		"                                                                                                                                                           MMMMMM                               ",
		"                                                   ZZZZZZ                                                                                                  MMMMMM                               ",
		"                                                   ZZZZZZ                                                                                                  MMMMMM                               ",
		"                                                   ZZZZZZ                                                                                                  MMMMMM                               ",
		"                                                   ZZZZZZ                                                                                                                                       ",
		"                                                   ZZZZZZ                                                                                                                                       ",
		"                                                   ZZZZZZ                                                                                                                                       ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                      =================================================                                                   ====================================================                  ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                      MMMMMM                                                                                    ",
		"                                                                           RRRRRR                     MMMMMM                                                                                    ",
		"                                                                           RRRRRR                     MMMMMM                                                                                    ",
		"                                                         DDDDDD            RRRRRR                     MMMMMM                                                                                    ",
		"                                                         DDDDDD            RRRRRR                     MMMMMM                                                                                    ",
		"                                                         DDDDDD            RRRRRR                     MMMMMM                                                                                    ",
		"                                                         DDDDDD            RRRRRR                                                                                                               ",
		"                                                         DDDDDD                                                                                                                                 ",
		"                                                         DDDDDD                                                                                                                                 ",
		"                                                                                                                                                                                                ",
		"                                                  =================================================================================                                                             ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                      RRRRRR    ",
		"====================================                                                                                                                                                  RRRRRR    ",
		"                                                                                                                                                                                      RRRRRR    ",
		"                                                                                                                                                                                      RRRRRR    ",
		"                                                                                                                                                                                      RRRRRR    ",
		"                                                                                                                                                                                      RRRRRR    ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                    ============================",
		"                                                                                                                                                                                       XXXXXXXXX",
		"                                                                                                                                                                                       X       X",
		"                                                                                                                                                                                       X       X",
		"                                                                                                                                                                                       X       X",
		"                                                                                                                                                    MMMMMM                             X       X",
		"                                                                                                                                                    MMMMMM                             X       X",
		"                                                                                                                                ZZZZZZ              MMMMMM                             X       X",
		"                                                                                                                                ZZZZZZ              MMMMMM                             X       X",
		"                                                                  RRRRRR                                                        ZZZZZZ              MMMMMM                             X       X",
		"                                                                  RRRRRR                                                        ZZZZZZ              MMMMMM                             X       X",
		"                                                                  RRRRRR                                                        ZZZZZZ                                                 X       X",
		"                                                                  RRRRRR                                                        ZZZZZZ                                                 X       X",
		"                                                                  RRRRRR                                                                                                               X       X",
		"                                                                  RRRRRR                                                                                                               X       X",
		"                                                                                                                                                                                       X       X",
		"                                                                                                                                                                                       X       X",
		"                                                                                                                                                                                       X       X",
		"================================================================================                                 ====================================================                  X       X",
		"                                                XXXXXXXXXXXXXXXXXXXX                                                         XXXXXXXXXXXXXXXXXXX                                       X       X",
		"XXXXX                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   X                                           X                  X                                                         X                 X                                       X       X",
		"X   XX                                          X                  X                                                         X                 X                                    XXXX       X",
		"X     XX                                        X                  X                                                         X                 X                                  XXX          X",
		"X      XXX                                      X                  X                                                         X                 X                                XXX            X",
		"X        XXX                  PPPPPP            X                  X                                                         X                 X                              XXX              X",
		"X          XX                 PPPPPP            X                  X                                                         X                 X                              X                X",
		"X           XXXX              PPPPPP            X                  X                                                         X                 X                              X                X",
		"X              XXX            PPPPPP            X                  X                                                         X                 X                              X                X",
		"X                X            PPPPPP            X                  X                                                         X                 X                              X                X",
		"X                X            PPPPPP            X                  X                                                         X                 X                              X                X",
		"XXXXXXXXXXXXXXXXXX##############################XXXXXXXXXXXXXXXXXXXX                                                         XXXXXXXXXXXXXXXXXXX##############################XXXXXXXXXXXXXXXXXX",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
	],
	2: [
		"XXXXXXXXXXXXX                                                                                                                                                                   XXXXXXXXXXXXXXXX",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                                                                                                                                                                   X              X",
		"X           X                             ZZZZZZ                                                                                                                                 X             X",
		"X          XX                             ZZZZZZ                                                                                                                                 XXX           X",
		"X          X                              ZZZZZZ                                                                                                                                   XX          X",
		"X         XX                              ZZZZZZ                                                                                                                                    X          X",
		"X         X                               ZZZZZZ                                                                                                                DDDDDD              XX         X",
		"X        XX                               ZZZZZZ                                                                                                                DDDDDD               XX        X",
		"X       XX                                                                                                                                                      DDDDDD                X        X",
		"X       X              ==============================================                                                                                           DDDDDD                XX       X",
		"X       X                                                                                                                                                       DDDDDD                 X       X",
		"X      XX                                                                                                                                                       DDDDDD                 XX      X",
		"X      X                                                                                                                                                                                X      X",
		"X      X                                                                                                                                                                                X      X",
		"X     XX                                                                                                                         ==========================================             X      X",
		"X     X                                                                                                                                                                                 XX     X",
		"X     X                                                                                                                                                                                 XX     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                            RRRRRR                                                                                                                                                X     X",
		"X     X                            RRRRRR                                                                                                                                                X     X",
		"X     XX                           RRRRRR                                                                                                                                                X     X",
		"X      X                           RRRRRR                                                                                                                                                X     X",
		"X      XX                          RRRRRR                                                                                                                                               XX     X",
		"X       X                          RRRRRR                                                                                                                                              X       X",
		"X       X                         ======================                                                                                                                               X       X",
		"X       X                                                                                                                                                                              X       X",
		"X       X                                                                                                                                                                              X       X",
		"X       X                                                                                                                                                                             XX       X",
		"X       X                                                                                                                                                          RRRRRR             X        X",
		"X       X                                                                                                                            ZZZZZZ                        RRRRRR             X        X",
		"X       X                                                                                                                            ZZZZZZ                        RRRRRR             X        X",
		"X       X                                                                                                                            ZZZZZZ                        RRRRRR             X        X",
		"X       X                                                                                                                            ZZZZZZ                        RRRRRR             X        X",
		"X       X                                                                                                                            ZZZZZZ                        RRRRRR             X        X",
		"X       X                                                                                                                            ZZZZZZ                                           X        X",
		"X       X                                                                                                                                                   =================         X        X",
		"X       X                       ZZZZZZ                                                                                      ====================                                      X        X",
		"X       X                       ZZZZZZ                                                                                                                                                X        X",
		"X       X                       ZZZZZZ                                                                                                                                                X        X",
		"X       X                       ZZZZZZ                                                                                                                                                X        X",
		"X       X                       ZZZZZZ                                                                                                                                                X        X",
		"X       X                       ZZZZZZ                                                                                                                                                X        X",
		"X       X                                                                                                                                                                             X        X",
		"X       X                 ==============                                                                                                                                              XX       X",
		"X       X                                                                                                                                                                              X       X",
		"X       X                                                                                                                                                                              X       X",
		"X       X                                                                                                                                                                              X       X",
		"X       X                                                                                                                                                                              X       X",
		"X      XX                                                                                                                                                                              X       X",
		"X     XX                                                                                                                                                                               XX      X",
		"X     X                                                  RRRRRR                                                                                                                         XX     X",
		"X     X                                                  RRRRRR                                                                    RRRRRR                                                X     X",
		"X     X                                                  RRRRRR                                                                    RRRRRR                                     MMMMMM     X     X",
		"X     X                                                  RRRRRR                                                                    RRRRRR                                     MMMMMM     X     X",
		"X     X                                                  RRRRRR                                                                    RRRRRR                                     MMMMMM     X     X",
		"X     X                                                  RRRRRR                                                                    RRRRRR                                     MMMMMM     X     X",
		"X     X                                                                                                                            RRRRRR                                     MMMMMM     X     X",
		"X     X                                                                                                                                                                       MMMMMM     X     X",
		"X     X                                          ==================                                                          ===================                                         X     X",
		"X     X====================                                                                                                                                             =================X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     X                                                                                                                                                                                  X     X",
		"X     XX                             PPPPPP                                                                                                                                             XX     X",
		"X      XX                            PPPPPP                                                                                                                                           XXX      X",
		"X       XXX                          PPPPPP                                                                                                                                         XXX        X",
		"X         XXX                        PPPPPP                                                                                                                                     XXXXX          X",
		"X           XXXX                     PPPPPP                                                                                                                                    XX              X",
		"X              XX                    PPPPPP                                                                                                                                   XX               X",
		"X               XX                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X###################################################                                                      ###################################################X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"X                X                                                                                                                                                            X                X",
		"XXXXXXXXXXXXXXXXXX                                                                                                                                                            XXXXXXXXXXXXXXXXXX",
	],
	3: [
		"XXXXXXXXXXXXXXXXXXXXXXXXX                                                                                                                                              XXXXXXXXXXXXXXXXXXXXXXXXX",
		"X                       X                                                                                                                                              XX                      X",
		"X                XXXXXXXX                                                                                                                                               XXXXXX                 X",
		"X              XXX                                                                                                                                                           XXXXXX            X",
		"X              X                                                                                                                                                                 X             X",
		"X             XX                                                                                                                                                                 X             X",
		"X             X                                                                                                                                                                  X             X",
		"X            XX                                                                                                                                                                  XXXXX  X      X",
		"X           XX                                                                                                                                                                       XXXX      X",
		"X           X                                                                                                                                                                           X      X",
		"X           X                                                                                                                                                                           X      X",
		"X           X                                                                                                                                                                           XX     X",
		"X          XX                                                                                                                                                                            X     X",
		"X          X                                                                                                                                                                             X     X",
		"X          X                                                                                                                                                                             X     X",
		"X     XXXXXX                                                                                                                                                                             XX    X",
		"X    XX                                                                                                                                                                                   XX   X",
		"X    X                                                                                                                                                                                     X   X",
		"X    X                                                                                                                                                                                     XX  X",
		"X XXXX                                                                                                                                                                                      XX X",
		"X X                                                                                                                                                              FFFFFF                      X X",
		"X X                                                                                                                                                              FFFFFF                      X X",
		"X X                                                                                                                                                              FFFFFF                      X X",
		"X X                                                                                                                                                              FFFFFF                      X X",
		"X X                                                                                                                                                              FFFFFF                      X X",
		"X X                                                                                                                                                              FFFFFF                      X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                   =======================================================================================================================================================================X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"X X                                                                                                                                                                                          X X",
		"XXX                                                                                                                                                                                          X X",
		"  =======================================================================================================================================================================                    X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"             PPPPPP                                                                                                                                                                          X X",
		"             PPPPPP                                                                                                                                                                          X X",
		"             PPPPPP                                                                                                                                                                          X X",
		"             PPPPPP                                                                                                                                                                          X X",
		"             PPPPPP                                                                                                                                                                          X X",
		"             PPPPPP                                                                                                                                                                          X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             X X",
		"                                                                                                                                                                                             XXX",
		"################################################################################################################################################################################################",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
	],
	4: [
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                  =====================================                                                                                                                                         ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"===================================================                                                                                                                                             ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                         BBBBBB                                                 ",
		"                                                                                                                                         BBBBBB                                                 ",
		"                                                                                                                                         BBBBBB                                                 ",
		"                                                                                                                                         BBBBBB                                                 ",
		"          ==================================================================                                                             BBBBBB                                                 ",
		"                                                                                                                                         BBBBBB                                                 ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                    PPPPPP                                                                                                                                                                      ",
		"                    PPPPPP                                                                                                                                                                      ",
		"                    PPPPPP                                                                                                                                                                      ",
		"                    PPPPPP                                                                                                                                                                      ",
		"                    PPPPPP                                                                                                                                                                      ",
		"                    PPPPPP                                                                                                                                                                      ",
		"######################################################################################                                                                                                          ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
	],
}

const TILE_SOURCES := {"#": 0, ".": 1, "=": 2}
const PICKUP_TYPES := {}

const FLOATING_PLATFORMS := {
	1: [
	],
	2: [
		{
			"texture_path": "res://assets/sprites/Chapter2/Chapter2_Platform1_01.png",
			"position": Vector2(960, 798),
			"scale": Vector2(0.5, 0.5),
			"move_left": 150,
			"move_right": 150,
			"move_up": 0,
			"move_down": 0,
			"speed": 80,
			"collision_cells": [
				Vector2i(5, 2), Vector2i(6, 2), Vector2i(7, 2), Vector2i(8, 2), Vector2i(9, 2), Vector2i(10, 2), Vector2i(11, 2), Vector2i(12, 2), Vector2i(13, 2), Vector2i(14, 2), Vector2i(15, 2), Vector2i(17, 2),
				Vector2i(19, 2), Vector2i(21, 2), Vector2i(23, 2), Vector2i(25, 2), Vector2i(27, 2), Vector2i(29, 2), Vector2i(31, 2), Vector2i(33, 2), Vector2i(35, 2), Vector2i(37, 2), Vector2i(39, 2), Vector2i(41, 2),
				Vector2i(43, 2), Vector2i(45, 2), Vector2i(47, 2), Vector2i(49, 2), Vector2i(4, 3), Vector2i(5, 3), Vector2i(6, 3), Vector2i(7, 3), Vector2i(8, 3), Vector2i(9, 3), Vector2i(10, 3), Vector2i(11, 3),
				Vector2i(12, 3), Vector2i(13, 3), Vector2i(14, 3), Vector2i(15, 3), Vector2i(16, 3), Vector2i(17, 3), Vector2i(18, 3), Vector2i(19, 3), Vector2i(20, 3), Vector2i(21, 3), Vector2i(22, 3), Vector2i(23, 3),
				Vector2i(24, 3), Vector2i(25, 3), Vector2i(26, 3), Vector2i(27, 3), Vector2i(28, 3), Vector2i(29, 3), Vector2i(30, 3), Vector2i(31, 3), Vector2i(32, 3), Vector2i(33, 3), Vector2i(34, 3), Vector2i(35, 3),
				Vector2i(36, 3), Vector2i(37, 3), Vector2i(38, 3), Vector2i(39, 3), Vector2i(40, 3), Vector2i(41, 3), Vector2i(42, 3), Vector2i(43, 3), Vector2i(44, 3), Vector2i(45, 3), Vector2i(46, 3), Vector2i(47, 3),
				Vector2i(48, 3), Vector2i(49, 3),
			],
		},
		{
			"texture_path": "res://assets/sprites/Chapter2/Chapter2_Platform2_01.png",
			"position": Vector2(954, 450),
			"scale": Vector2(0.4, 0.4),
			"move_left": 0,
			"move_right": 0,
			"move_up": 110,
			"move_down": 110,
			"speed": 70,
			"collision_cells": [
				Vector2i(2, 2), Vector2i(3, 2), Vector2i(4, 2), Vector2i(5, 2), Vector2i(6, 2), Vector2i(7, 2), Vector2i(8, 2), Vector2i(9, 2), Vector2i(10, 2), Vector2i(11, 2), Vector2i(12, 2), Vector2i(13, 2),
				Vector2i(14, 2), Vector2i(15, 2), Vector2i(16, 2), Vector2i(17, 2), Vector2i(18, 2), Vector2i(19, 2), Vector2i(20, 2), Vector2i(21, 2), Vector2i(22, 2), Vector2i(23, 2), Vector2i(24, 2), Vector2i(25, 2),
				Vector2i(26, 2), Vector2i(27, 2), Vector2i(28, 2), Vector2i(29, 2), Vector2i(30, 2), Vector2i(31, 2), Vector2i(32, 2), Vector2i(33, 2), Vector2i(34, 2), Vector2i(35, 2), Vector2i(36, 2), Vector2i(37, 2),
				Vector2i(38, 2), Vector2i(39, 2), Vector2i(40, 2), Vector2i(41, 2), Vector2i(42, 2), Vector2i(43, 2), Vector2i(2, 3), Vector2i(3, 3), Vector2i(4, 3), Vector2i(5, 3), Vector2i(6, 3), Vector2i(7, 3),
				Vector2i(8, 3), Vector2i(9, 3), Vector2i(10, 3), Vector2i(11, 3), Vector2i(12, 3), Vector2i(13, 3), Vector2i(14, 3), Vector2i(15, 3), Vector2i(16, 3), Vector2i(17, 3), Vector2i(18, 3), Vector2i(19, 3),
				Vector2i(20, 3), Vector2i(21, 3), Vector2i(22, 3), Vector2i(23, 3), Vector2i(24, 3), Vector2i(25, 3), Vector2i(26, 3), Vector2i(27, 3), Vector2i(28, 3), Vector2i(29, 3), Vector2i(30, 3), Vector2i(31, 3),
				Vector2i(32, 3), Vector2i(33, 3), Vector2i(34, 3), Vector2i(35, 3), Vector2i(36, 3), Vector2i(37, 3), Vector2i(38, 3), Vector2i(39, 3), Vector2i(40, 3), Vector2i(41, 3), Vector2i(42, 3), Vector2i(43, 3),
				Vector2i(3, 4), Vector2i(4, 4), Vector2i(5, 4), Vector2i(6, 4), Vector2i(7, 4), Vector2i(8, 4), Vector2i(9, 4), Vector2i(10, 4), Vector2i(11, 4), Vector2i(12, 4), Vector2i(13, 4), Vector2i(14, 4),
				Vector2i(15, 4), Vector2i(16, 4), Vector2i(17, 4), Vector2i(18, 4), Vector2i(19, 4), Vector2i(20, 4), Vector2i(21, 4), Vector2i(22, 4), Vector2i(23, 4), Vector2i(24, 4), Vector2i(25, 4), Vector2i(26, 4),
				Vector2i(27, 4), Vector2i(28, 4), Vector2i(29, 4), Vector2i(30, 4), Vector2i(31, 4), Vector2i(32, 4), Vector2i(33, 4), Vector2i(34, 4), Vector2i(35, 4), Vector2i(36, 4), Vector2i(37, 4), Vector2i(38, 4),
				Vector2i(39, 4), Vector2i(40, 4), Vector2i(41, 4), Vector2i(42, 4),
			],
		},
	],
	3: [
	],
	4: [
	],
}
