extends Node

const LEVELS := {
	1: [
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                           MMMMMM                               ",
		"                                                                                                                                                           MMMMMM                               ",
		"                                                                                                                                                           MMMMMM                               ",
		"                                                   ZZZZZZ                                                                                                  MMMMMM                               ",
		"                                      aaaaaa       ZZZZZZ                                                                   hhhhhh             BBBBBB      MMMMMM                               ",
		"                                      aaaaaa       ZZZZZZ                                                                   hhhhhh             BBBBBB      MMMMMM                               ",
		"                                      aaaaaa       ZZZZZZ                                                                   hhhhhh             BBBBBB                                           ",
		"                                      aaaaaa       ZZZZZZ                                                                   hhhhhh             BBBBBB                                           ",
		"                                      aaaaaa       ZZZZZZ                                                                   hhhhhh             BBBBBB                                           ",
		"                                      aaaaaa                                                                                hhhhhh             BBBBBB                                           ",
		"                                                                                                                                                                                                ",
		"                      =================================================                                                   ====================================================                  ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                      MMMMMM                                                                                    ",
		"                                                                           RRRRRR                     MMMMMM                                                                                    ",
		"                                                                           RRRRRR                     MMMMMM                                                                                    ",
		"                                                         DDDDDD            RRRRRR SSSSSS              MMMMMM         GGGGGG                                                                     ",
		"                                                         DDDDDD            RRRRRR SSSSSS              MMMMMM         GGGGGG                                                                     ",
		"                                                         DDDDDD            RRRRRR SSSSSS              MMMMMM         GGGGGG                                                                     ",
		"                                                         DDDDDD            RRRRRR SSSSSS                             GGGGGG                                                                     ",
		"                                                         DDDDDD                   SSSSSS                             GGGGGG                                                                     ",
		"                rrrrrr                                   DDDDDD                   SSSSSS                             GGGGGG                                                                     ",
		"                rrrrrr                                                                                                                                                                          ",
		"                rrrrrr                            =================================================================================                                                             ",
		"                rrrrrr                                                                                                                                                                          ",
		"                rrrrrr                                                                                                                                                                          ",
		"                rrrrrr                                                                                                                                                                RRRRRR    ",
		"====================================                                                                                                                                         cccccc   RRRRRR    ",
		"                                                                                                                                                                         rrrrrrcccc   RRRRRR    ",
		"                                                                                                                                                                         rrrrrrcccc   RRRRRR    ",
		"                                                                                                                                                                         rrrrrrcccc   RRRRRR    ",
		"                                                                                                                                                                         rrrrrrcccc   RRRRRR    ",
		"                                                                                                                                                                         rrrrrrcccc             ",
		"                                                                                                                                                                         rrrrrr                 ",
		"                                                                                                                                                                    ============================",
		"                                                                                                                                                                                       XXXXXXXXX",
		"                                                                                                                                                                                       X        ",
		"                                                                                                                                                                                       X        ",
		"                                                                                                                                                                                       X        ",
		"                                                                                                                                                    MMMMMM                             X        ",
		"                                                                                                                                                    MMMMMM                             X        ",
		"                                                                                                                                ZZZZZZ              MMMMMM                             X        ",
		"                                                                                                                                ZZZZZZ              MMMMMM                             X        ",
		"                                                                  RRRRRR                                                        ZZZZZZ              MMMMMM                             X        ",
		"                                                                  RRRRRR                                                        ZZZZZZ              MMMMMM                             X        ",
		"                                                                 GRRRRRR                                                        ZZZZZZ                                                 X        ",
		"                                                                 GRRRRRR                                                        ZZZZZZ                                                 X        ",
		"                                                                 GRRRRRR                                                                                                               X        ",
		"                                                                 GRRRRRR                                                                                                               X        ",
		"                                                                 GGGGGG                                                                    G                                           X        ",
		"                                                                 GGGGGG                                                               GGGGGG                                           X        ",
		"                                                                                                                                                                                       X        ",
		"================================================================================                                 ====================================================                  X        ",
		"================================================================================                                             XXXXXXXXXXXXXXXXXXX                                       X        ",
		"XXXXX                                           XXXXXXXXXXXXXXXXXXXX                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    X                                           X                  X                                                         X                 X                                       X        ",
		"    XX                                          X                  X                                                         X                 X                                    XXXX        ",
		"      XX                                        X                  X                                                         X                 X                                  XXX           ",
		"       XXX                                      X                  X                                                         X                 X                                XXX             ",
		"         XXX                  PPPPPP            X                  X                                                         X                 X             rrrrrr           XXX               ",
		"           XX                 PPPPPP            X                  X                                                         X                 X             rrrrrr           X                 ",
		"            XXXX              PPPPPP            X                  X                                                         X                 X             rrrrrr           X                 ",
		"               XXX            PPPPPP            X                  X                                                         X                 X             rrrrrr           X                 ",
		"                 X            PPPPPP            X                  X                                                         X                 X             rrrrrr           X                 ",
		"                 X            PPPPPP            X                  X                                                         X                 X             rrrrrr           X                 ",
		"XXXXXXXXXXXXXXXXXX##############################XXXXXXXXXXXXXXXXXXXX                                                         XXXXXXXXXXXXXXXXXXX##############################XXXXXXXXXXXXXXXXXX",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
		"                                                                                                                                                                                                ",
	],
}

const TILE_SOURCES := {"#": 0, ".": 1, "=": 2}
const PICKUP_TYPES := {"a": 0, "c": 1, "r": 2, "h": 3}
